#!/bin/sh
PATH=.:$PATH

# Edit these to match your configuration
TAPE=../tapes
DASD=../dasd

#
# Run CTSS diagnostic image
#
if [ "$1" = "" ];then
   echo "usage: diagctss ctssdiagtape [commands] [s709options] [ioassignments]"
   exit 1
fi

if [ "$2" = "" ]; then
   echo "stop" >cmd.txt
else
   cp $2 cmd.txt
fi
txt2bcd cmd.txt cmd.bcd 80 80
bcd2cbn cmd

#
# Run.
#
rm -f trace.bin
s709 $3 -C8 -mCTSS -cdiagctss.cmd r=cmd p=print \
	a1r=$1 $4 $5 $6 $7 \
	cd00=${DASD}/DISK1.BIN cn01=${DASD}/DRUM1.BIN cd42=${DASD}/DISK2.BIN \
	ec32=2023:KSR-35 gh00=${DASD}/DRUM2.BIN gh01=${DASD}/DRUM3.BIN
#
rm -f cmd.txt cmd.bcd cmd.cbn
