#!/bin/sh
PATH=.:$PATH

# Edit these to match your configuration
TAPE=../tapes
DASD=../dasd

# Install the CTSS tapes

setupctss ${TAPE}/com3.tap
setupctss ${TAPE}/com1.tap
setupctss ${TAPE}/com2.tap
setupctss ${TAPE}/com4.tap
setupctss ${TAPE}/com5.tap
setupctss ${TAPE}/lisp.tap
setupctss ${TAPE}/comlinks.tap
cleanupctss
setupctss ${TAPE}/comdata.tap
setupctss ${TAPE}/quotas.tap
setupctss ${TAPE}/fibmon.tap
setupctss ${TAPE}/util.tap
setupctss ${TAPE}/cmfl01.tap
setupctss ${TAPE}/guest.tap
setupctss ${TAPE}/progs.tap
cleanupctss
