#!/bin/sh
PATH=.:$PATH

# Report on CTSS users

usage()
{
   echo "reportuserctss [options] [programmername]"
   echo "  options:"
   echo "   -d"
   echo "   -p projectname"
}

projectname="M1416"
programmername="___ALL"
detail=0

# Process options.

while getopts ":dp:" opt; do
   case $opt in
   d)
      detail=1
      ;;
   p)
      projectname=`echo ${OPTARG} | tr [a-z] [A-Z]`
      ;;
   \? )
      echo "option -${OPTARG} unknown"
      usage
      exit 1
      ;;
   :)
      echo "option -${OPTARG} requires value"
      usage
      exit 1
      ;;
   esac
done
shift $(($OPTIND - 1))

if [ $# -eq 1 ]; then
   programmername=`echo $1 | tr [a-z] [A-Z]`
fi

# Get the current info.

extractctss B uaccnt timacc m1416 cmfl02 uaccnt.bcd >rptuserctss.log 2>&1
if [ $? -ne 0 ]; then
   echo "Error reading UACCNT file:"
   cat rptuserctss.log
   exit 1
fi
bcd2txt uaccnt.bcd uaccnt.data 168 168

extractctss B timusd timacc m1416 cmfl02 timusd.bcd >rptuserctss.log 2>&1
if [ $? -ne 0 ]; then
   echo "Error reading TIMUSD file:"
   cat rptuserctss.log
   exit 1
fi
bcd2txt timusd.bcd timusd.data 168 168

extractctss T report timacc m1416 cmfl02 report.data >rptuserctss.log 2>&1
if [ $? -ne 0 ]; then
   echo "Error reading REPORT file:"
   cat rptuserctss.log
   exit 1
fi
rm -f rptuserctss.log

# Go generate the report

userreportctss ${programmername} ${projectname} ${detail}

rm -f timusd.* uaccnt.* report.* rptuserctss.log
