#!/bin/sh
PATH=.:$PATH

# Edit these to match your configuration
TAPE=../tapes
DASD=../dasd

#
# Run CTSS.
#
# Usage: runctss [cardreader] [s709options] [device assignments]

if [ "$1" = "" ]; then
   echo "stop" >cmd.txt
else
   cp $1 cmd.txt
fi
txt2bcd cmd.txt cmd.bcd 80 80
bcd2cbn cmd

#
# Run CTSS image
#
rm -f ${TAPE}/trace.bin
s709 $2 -C8 -mCTSS -crunctsst.cmd r=cmd p=print \
	a1r=${TAPE}/ctss.tap a9=trace.bin $3 $4 $5 $6 $7 \
	cd00=${DASD}/DISK1.BIN cn01=${DASD}/DRUM1.BIN cd42=${DASD}/DISK2.BIN \
	ec32=2023 gh00=${DASD}/DRUM2.BIN gh01=${DASD}/DRUM3.BIN
#
rm -f cmd.txt cmd.bcd cmd.cbn
