#!/bin/sh
PATH=.:$PATH

# Edit these to match your configuration
TAPE=../tapes
DASD=../dasd

#
# Run CTSS Setup Job using tape as load.
#
if [ "$1" = "" ];then
   echo "usage: setupctss setupimage [s709options]"
   exit 1
fi

#
# Run CTSS image
#
rm -f trace.bin
s709 $2 -C8 -mCTSS -cutilctss.cmd p=print \
	a1r=${TAPE}/setup.tap a9=trace.bin b2r=$1 $3 $4 $5 $6 \
	cd00=${DASD}/DISK1.BIN cn01=${DASD}/DRUM1.BIN cd42=${DASD}/DISK2.BIN  \
	gh00=${DASD}/DRUM2.BIN gh01=${DASD}/DRUM3.BIN
