#!/bin/sh
PATH=.:$PATH

#
# Run IBSYS Job using tape as input, using 2 channels. simh format.
#
if [ "$1" = "" -o "$2" = "" ];then
   echo "usage: runibsys2s program listing [s709options]"
   exit 1
fi
rm -f punch.* print.* sysou* sys*.bin $2
#
# Make sysin file
#
gendate >sysin.txt
#cat ibsysc.ctl >>sysin.txt
cat $1 >>sysin.txt
cat eof.dat >>sysin.txt
cat ibsys.ctl >>sysin.txt
txt2bcd -s sysin
#
txt2bcd ibsys.ctl reader.bcd 80 80
bcd2cbn reader
#
# Run IBSYS
#
s709 $3 -cibsys.cmd -m7094 r=reader p=print u=punch \
	a1rs=../tapes/ASYS12s.BIN a2rs=../tapes/ASYS8s.BIN  \
	a3s=sysin.bcd  a4s=syslb4.bin  a5s=sysut1.bin a6s=sysut3.bin \
	a7s=sysck2.bin \
	b1s=sysou1.bcd b2s=sysou2.bcd b3s=syspp1.bin b4s=syspp2.bin \
	b5s=sysut2.bin b6s=sysut4.bin 
#
# Convert printed output
#
bcd2txt -sp sysou1.bcd $2
rm -f reader.* sysck*.bin print.bcd sysou1.* sysin.*
