#!/bin/sh
PATH=.:$PATH

#
# Run IBSYS Job using tape as input, with alternate BCD.
#
if [ "$1" = "" -o "$2" = "" ];then
   echo "usage: runibsys program listing [s709options]"
   exit 1
fi
rm -f punch.* print.* sysou1.* sys*.bin $2
#
# Make sysin tape.
#
gendate >sysin.txt
cat $1 >>sysin.txt
cat eof.dat >>sysin.txt
cat ibsys.ctl >>sysin.txt
txt2bcd -a sysin
#
txt2bcd ibsys.ctl reader.bcd 80 80
bcd2cbn reader
#
# Run IBSYS
#
s709 $3 -a -cibsys.cmd -m7094 r=reader p=print u=punch \
	a1r=ASYS1.BIN a2r=ASYS8.BIN  a3=sysin.bcd  a4=sysou1.bcd \
	a5=sysut1.bin  a6=sysut3.bin a7=sysut2.bin a8=syspp1.bin \
	a9=sysut4.bin a10=sysck2.bin 
#
# Convert printed output
#
bcd2txt -ap sysou1.bcd $2
rm -f reader.* print.bcd sysou1.* sysin.* sysck2.*
